# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57819661be2588041d4a544f36248dc8ddd5e00fea86ab6c1fd017ffd90ee1b9e7a1245e2bc1f2ca3ceace0b562f7d2997787077b7367981de1a9a97789dde7f

test:
  secret_key_base: 07e7fef21f5d7ec8247a46b43fe1e0a722891fdaa1e6a3facc82617dd97824b7f4070ebd0b0aea52d898587f9147cf4e265ff19d56412ef2721a2f8cec3a9d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
